# Generated by Django 4.0.5 on 2022-06-21 08:40

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(help_text='The minimum package price is 120,000/= per year ', validators=[django.core.validators.MinValueValidator(120000)])),
                ('status', models.CharField(default='active', max_length=10)),
            ],
            options={
                'ordering': ['created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(choices=[('multipurpose', 'multipurpose'), ('savings', 'savings'), ('loans', 'loans')], default='savings', max_length=40)),
                ('TIN', models.CharField(max_length=80, unique=True)),
                ('district', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('by_laws', models.FileField(blank=True, null=True, upload_to='by_laws')),
                ('permit', models.FileField(upload_to='permit')),
                ('recommendation', models.FileField(upload_to='recommendation')),
                ('status', models.CharField(default='inactive', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bussiness_creator', to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_director', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bussiness_package', to='core.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussiness_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=90, null=True)),
                ('url', models.URLField(blank=True, max_length=90, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sacco')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SaccoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='business', to='core.sacco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sacco users',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('expiry_date', models.DateTimeField(validators=[core.validators.expire_now_or_future])),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=10)),
                ('sacco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_license', to='core.sacco')),
            ],
            options={
                'ordering': ['-created_on', '-updated_on'],
                'unique_together': {('key', 'sacco')},
            },
        ),
    ]
