# Generated by Django 4.0.5 on 2022-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_tin_sacco_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacco',
            name='incorporation',
            field=models.FileField(default=1, upload_to='certificates'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sacco',
            name='recommendation',
            field=models.FileField(help_text='Recommendation from LC1', upload_to='recommendation'),
        ),
    ]
