# Generated by Django 4.0.5 on 2022-06-21 09:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sacco_incorporation_alter_sacco_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='by_laws',
            field=models.FileField(blank=True, null=True, upload_to='by_laws', validators=[core.validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='incorporation',
            field=models.FileField(help_text='Certificate of incorporation', upload_to='certificates', validators=[core.validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='permit',
            field=models.FileField(upload_to='permit', validators=[core.validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='recommendation',
            field=models.FileField(help_text='Recommendation from LC1', upload_to='recommendation', validators=[core.validators.image_validator]),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='tin',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
