# Generated by Django 4.0.5 on 2022-06-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_package_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(choices=[('120000', '120000'), ('240000', '240000')], default='120000', max_length=9),
        ),
    ]
