# Generated by Django 4.0.5 on 2022-06-17 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sacco_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(help_text='The minimum value is 120,000 per year ', validators=[django.core.validators.MinValueValidator(120000)]),
        ),
    ]
