# Generated by Django 4.0.5 on 2022-06-18 07:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(help_text='The minimum package price is 120,000/= per year ', validators=[django.core.validators.MinValueValidator(120000)]),
        ),
        migrations.CreateModel(
            name='UserSacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.sacco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sacco')},
            },
        ),
    ]
