# Generated by Django 4.0.5 on 2022-06-18 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_package_price_usersacco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSacco',
            new_name='SaccoUser',
        ),
    ]
