# Generated by Django 4.0.5 on 2022-06-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_usersacco_saccouser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saccouser',
            options={'verbose_name': ['Sacco users']},
        ),
        migrations.AlterUniqueTogether(
            name='saccouser',
            unique_together=set(),
        ),
    ]
