# Generated by Django 4.0.5 on 2022-06-18 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_saccouser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saccouser',
            options={'verbose_name_plural': 'Sacco users'},
        ),
        migrations.AlterField(
            model_name='saccouser',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sacco', to='core.sacco'),
        ),
        migrations.AlterField(
            model_name='saccouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
