# Generated by Django 4.0.5 on 2022-06-20 06:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_saccouser_sacco_alter_saccouser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('sacco', models.DateTimeField(verbose_name=core.models.Sacco)),
                ('event', models.CharField(max_length=90, null=True)),
                ('url', models.URLField(blank=True, max_length=90, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='active', max_length=10),
        ),
    ]
