# Generated by Django 4.0.5 on 2022-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_employer_type_alter_user_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national', 'national'), ('passport', 'passport'), ('other', 'other')], default='national', max_length=20),
        ),
    ]
